<?php
/**
 * @file
 * Openlayers Custom Controls
 */

/**
 * Implements hook_ctools_plugin_api()
 */
function openlayers_customcontrols_ctools_plugin_api($module, $api) {
  $path = drupal_get_path('module', 'openlayers_customcontrols') . '/includes';
  return array(
    'version' => 1,
    'path' => $path,
  );
}
function openlayers_customcontrols($form, &$form_state, $map_arg = NULL) {
	$path = drupal_get_path('module','openlayers_customcontrol');
	
	$form['#attach']['customcontrolpath'] = array(
		'#path' => $path,
	);
	return $form;
}