<?php
/**
 * @file
 * Openlayers Custom Controls
 */

/**
 * Implements hook_ctools_plugin_api()
 */
function openlayers_customcontrols_ctools_plugin_api($module, $api) {
  $path = drupal_get_path('module', 'openlayers_customcontrols') . '/includes';
  return array(
    'version' => 1,
    'path' => $path,
  );
}

function openlayers_customcontrols($form, &$form_state, $map_arg = NULL) {
	$path = drupal_get_path('module','openlayers_customcontrol');
	
	$form['#attach']['customcontrolpath'] = array(
		'#path' => $path,
	);
	return $form;
}

/**
 * Implements hook_libraries_info().
 */

function openlayers_customcontrols_preprocess_html(&$variables)
{
    drupal_add_js(libraries_get_path('treeview') .'/src/js/bootstrap-treeview.js', array('type' => 'file', 'scope' => 'footer'));
}


function openlayers_customcontrols_libraries_info()
{
    $libraries['treeview'] = array(
        'name' => 'Simple library', 
        'vendor url' => 'https://github.com/jonmiles/bootstrap-treeview', 
        'download url' => 'https://github.com/jonmiles/bootstrap-treeview.git', 
        'path' => 'lib',
      //    // Optional: Define a custom version detection callback, if required. 
      //    
      //    // Specify arguments for the version callback. By default,
      //    // libraries_get_version() takes a named argument array: 
      //    'version arguments' => array(
      //      'file' => 'docs/CHANGELOG.txt', 
      //      'pattern' => '@version\s+([0-9a-zA-Z\.-]+)@', 
      //      'lines' => 5, 
      //      'cols' => 20,
      //    ),
        // Default list of files of the library to load. Important: Only specify
        // third-party files belonging to the library here, not integration files of
        // your module. 
        'files' => array(
            'js' => array(
                'bootstrap-treeview/src/js/bootstrap-treeview.js',
            )
        ),
    );
    return $libraries;  
}